#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 192.168.3.19
    port: 6379
    password: longqi@1314
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    url: jdbc:mysql://192.168.3.19:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: longqi@1314
    driver-class-name: com.mysql.cj.jdbc.Driver

